In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle


In [65]:
#utils

def carregar_pickle(nome_arquivo):
  with open(nome_arquivo, 'rb') as arquivo:
    objeto = pickle.load(arquivo)
  return objeto

In [66]:
raw_data_set = carregar_pickle('dataset_human_v2.pkl')
input_full = raw_data_set['inputs']
output_full = raw_data_set['outputs']
sequences_full = raw_data_set['sequences']

In [16]:
input_full.shape

(106, 54, 16)

In [67]:
input_train, input_test, output_train, output_test, sequence_train, sequence_test = train_test_split(input_full, output_full, 
sequences_full, train_size=0.75 , shuffle= True, random_state = 0);

In [158]:
input_train.shape

(79, 54, 16)

In [69]:
#utils

def myClassify(array, corte):
    classifiedArray = []
    for x in array:
        if(x > corte):
            classifiedArray.append(1)
        else:
            classifiedArray.append(0)
    
    return classifiedArray


def comparePredictOkNok(arrPredict, arrReal, size):
    arrOkNok = []
    for i in range(0, size):
        if(arrPredict[i] == arrReal[i]):
            arrOkNok.append('OK')
        else:
            arrOkNok.append('NOK')
    
    return arrOkNok

        


In [110]:
input_train[0].shape

(16, 54)

In [70]:
CNN = keras.Sequential()
CNN.add(keras.layers.Conv1D(10, kernel_size= 1, strides= 1, padding='valid', 
                            activation='relu', input_shape = (54, 16), use_bias= False))
#CNN.add(keras.layers.AveragePooling1D(pool_size=2, strides= 1, padding='valid'))
CNN.add(keras.layers.Flatten())
CNN.add(keras.layers.Dense(256, activation='relu'))
CNN.add(keras.layers.Dense(64, activation='relu'))
CNN.add(keras.layers.Dense(10, activation='relu'))
CNN.add(keras.layers.Dense(1, activation='sigmoid'))



In [71]:
CNN.summary();
keras.utils.plot_model(CNN);

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_5 (Conv1D)           (None, 54, 10)            160       
                                                                 
 flatten_5 (Flatten)         (None, 540)               0         
                                                                 
 dense_20 (Dense)            (None, 256)               138496    
                                                                 
 dense_21 (Dense)            (None, 64)                16448     
                                                                 
 dense_22 (Dense)            (None, 10)                650       
                                                                 
 dense_23 (Dense)            (None, 1)                 11        
                                                                 
Total params: 155,765
Trainable params: 155,765
Non-tr

In [72]:
CNN.compile(loss=keras.losses.BinaryCrossentropy(reduction='sum_over_batch_size'), metrics=['accuracy'])

In [73]:
CNN.fit(input_train, output_train, epochs= 50, batch_size = 1)

Epoch 1/50
79/79 [==============================] - 2s 6ms/step - loss: 0.7128 - accuracy: 0.5190
Epoch 2/50
79/79 [==============================] - 1s 7ms/step - loss: 0.4054 - accuracy: 0.8101
Epoch 3/50
79/79 [==============================] - 1s 7ms/step - loss: 0.1503 - accuracy: 0.9494
Epoch 4/50
79/79 [==============================] - 1s 11ms/step - loss: 0.0271 - accuracy: 0.9873
Epoch 5/50
79/79 [==============================] - 1s 10ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 6/50
79/79 [==============================] - 1s 7ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 7/50
79/79 [==============================] - 1s 7ms/step - loss: 1.0172e-04 - accuracy: 1.0000
Epoch 8/50
79/79 [==============================] - 1s 10ms/step - loss: 0.0021 - accuracy: 1.0000
Epoch 9/50
79/79 [==============================] - 1s 7ms/step - loss: 3.4568e-06 - accuracy: 1.0000
Epoch 10/50
79/79 [==============================] - 1s 7ms/step - loss: 6.6768e-07 - accuracy: 1.0000
Epoc

In [75]:

CNN.evaluate(input_test, output_test, batch_size= 1)





27/27 [==============================] - 0s 4ms/step - loss: 0.3340 - accuracy: 0.8889


[0.3339799642562866, 0.8888888955116272]

In [76]:
predictOnTest = CNN.predict(input_test)
predictOnTest

1/1 [==============================] - 0s 138ms/step


array([[2.6934301e-03],
       [1.0000000e+00],
       [7.4267619e-09],
       [1.8650150e-01],
       [9.9999946e-01],
       [4.7532914e-04],
       [6.0492891e-07],
       [1.0000000e+00],
       [9.9999988e-01],
       [8.8666808e-15],
       [6.6278074e-07],
       [1.0000000e+00],
       [1.0000000e+00],
       [6.7931043e-09],
       [3.4478093e-03],
       [9.9962473e-01],
       [9.9999899e-01],
       [2.8085253e-01],
       [1.8613224e-01],
       [5.0855637e-01],
       [6.0317669e-13],
       [9.9999964e-01],
       [1.0000000e+00],
       [1.6108155e-10],
       [1.0000000e+00],
       [2.2768204e-03],
       [1.0739287e-04]], dtype=float32)

In [77]:
output_test

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0])

In [78]:
classifiedArrayPredict = myClassify(predictOnTest, 0.5)
np.array(classifiedArrayPredict)

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0])

In [79]:

comparePredictOkNok(classifiedArrayPredict, output_test, output_test.shape[0])

['OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK',
 'OK',
 'OK',
 'OK',
 'OK',
 'NOK',
 'OK']

In [94]:
CNN.layers[0].get_weights()[0][0]

array([[ 0.23533559,  0.42990232, -0.25082487, -0.15267515,  0.26705414,
         0.41497964,  0.27988416,  0.37338895, -0.29958403, -0.04501176],
       [ 0.42684212,  0.07528386,  0.28260273, -0.10901958, -0.15239488,
         0.44041243,  0.01431945,  0.2730652 ,  0.4608476 ,  0.46495697],
       [ 0.45438316,  0.02100177,  0.29724106, -0.24716143, -0.4676595 ,
         0.4724816 , -0.3817394 ,  0.19320472,  0.42271256, -0.05679994],
       [ 0.15253878, -0.10971248, -0.04070297, -0.21874414, -0.08176634,
         0.28545243, -0.43704703,  0.18602677,  0.22525644,  0.47238237],
       [-0.46574974, -0.4418646 , -0.38255867, -0.34078255, -0.23755996,
         0.2713209 ,  0.27443305, -0.03233695,  0.24816659, -0.28621373],
       [ 0.07085161,  0.39532802, -0.03007789, -0.32714292,  0.49284223,
         0.18271512, -0.03359003, -0.21458982, -0.42486927,  0.06511235],
       [ 0.2713358 , -0.27115414,  0.34532204, -0.23495436, -0.43641958,
        -0.3368862 ,  0.12960823,  0.10995054